export const SET_CHAT_ROOM_MOBILE = 'SET_CHAT_ROOM_MOBILE';
export const SET_FOCUS_PLAYER = 'SET_FOCUS_PLAYER';
export const SET_OPEN_SETTING = 'SET_OPEN_SETTING';
export const SET_RESOLUTION = 'SET_RESOLUTION';
